x-common-service: &common-service
  image: "${IMAGE}"
  privileged: true
  sysctls:
    kernel.sem: 500 1024000 200 4096
  init: true
  ulimits:
    nofile: 65535
  entrypoint: >
    sleep infinity

services:
  cdw:
    <<: *common-service
    working_dir: /home/gpadmin
    hostname: cdw
    volumes:
      - ${PWD}/allure-results:/tmp/allure-results
      - ${PWD}/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
      - ${PWD}/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ${PWD}/logs_cdw/gpAdminLogs:/home/gpadmin/gpAdminLogs
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/gpAdminLogs
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/standby
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
      - ${PWD}/logs_cdw/isolation2:/home/gpadmin/gpdb_src/src/test/isolation2/results
      - ${PWD}/logs_cdw/isolation2:/home/gpadmin/gpdb_src/src/test/isolation2/regression.diffs
  sdw1:
    <<: *common-service
    hostname: sdw1
    volumes:
      - ${PWD}/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
      - ${PWD}/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ${PWD}/logs_cdw/gpAdminLogs:/home/gpadmin/gpAdminLogs
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/gpAdminLogs
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/standby
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
      - ${PWD}/logs_cdw/datadirs:/home/gpadmin/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
      - ${PWD}/logs_cdw/isolation2:/home/gpadmin/gpdb_src/src/test/isolation2/results
      - ${PWD}/logs_cdw/isolation2:/home/gpadmin/gpdb_src/src/test/isolation2/regression.diffs
  sdw2:
    <<: *common-service
    hostname: sdw2
    volumes:
      - ${PWD}/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
      - ${PWD}/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ${PWD}/logs_sdw2:/logs
  sdw3:
    <<: *common-service
    hostname: sdw3
    volumes:
      - ${PWD}/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
      - ${PWD}/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ${PWD}/logs_sdw3:/logs
