x-common-service: &common-service
  image: "${IMAGE}"
  privileged: true
  sysctls:
    kernel.sem: 500 1024000 200 4096
  init: true
  ulimits:
    nofile: 65535
  entrypoint: >
    sleep infinity

x-common-volumes: &common-volumes
  volumes:
    - $PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
    - $PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
    - $PWD/sqldump/dump.sql:/home/gpadmin/sqldump/dump.sql

services:
  cdw:
    <<: [*common-service, *common-volumes]
    working_dir: /home/gpadmin
    hostname: cdw
    volumes:
      - $PWD/allure-results:/tmp/allure-results
      - $PWD/logs_cdw:/logs

  sdw1:
    <<: [*common-service, *common-volumes]
    hostname: sdw1
    volumes:
      - $PWD/logs_sdw1:/logs

  sdw2:
    <<: [*common-service, *common-volumes]
    hostname: sdw2
      - $PWD/logs_sdw2:/logs

  sdw3:
    <<: [*common-service, *common-volumes]
    hostname: sdw3
      - $PWD/logs_sdw3:/logs
